---
abstract: ~
author:
  - 'Evan Carroll <me+cpan@evancarroll.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.81'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Olson-Abbreviations
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::AttributeHelpers: 0
  MooseX::ClassAttribute: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/EvanCarroll/olson-abbreviations.git
version: 0.01
